import pandas as pd
import numpy as np
import yfinance as yf
import math
import os
#print(os.getcwd())

'''
Opening the CSV file containing daily returns, as generated by asset_import.py
Index column of returns starts from 25 (Z), and index row starts from 2, till the end.
'''
return_matrix = pd.read_csv("asset_prices_returns.csv", header=None, 
                            skiprows=1, index_col=25);
print ("Return Matrix:\n", return_matrix)



