import pandas as pd
import numpy as np
import yfinance as yf
import math
import os
#print(os.getcwd())

'''
Opening the CSV file containing daily returns, as generated by asset_import.py
Index column of returns starts from 25 (Z), and index row starts from 2, till the end.
'''
returns = pd.read_csv("asset data/asset_prices_returns.csv",parse_dates=["Date"])
return_matrix = returns.iloc[:,25:]
return_matrix.index=returns["Date"]
return_matrix.index.name = "Date"

return_matrix = return_matrix.dropna()
print ("Return Matrix:\n", return_matrix.head())

total_rows = return_matrix.shape[0]
rolling_period = return_matrix[return_matrix.index.year == 2020].shape[0] # number of daily returns
total_months = return_matrix.groupby(pd.Grouper(freq="ME")).tail(1).index # number of months
#print ("Total Months:", total_months)

rolling_windows = sum(return_matrix.index.get_loc(date) >= rolling_period 
                      for date in total_months)
print ("Rolling Windows:", rolling_windows)




