import pandas as pd
import numpy as np
import yfinance as yf
import math
import os
from scipy.optimize import minimize

#print(os.getcwd())

'''
Opening the CSV file containing daily returns, as generated by asset_import.py
Index column of returns starts from 25 (Z), and index row starts from 2, till the end.
'''
returns = pd.read_csv("asset data/asset_prices_returns.csv",parse_dates=["Date"])
return_matrix = returns.iloc[:,25:]
return_matrix.index=returns["Date"]
return_matrix.index.name = "Date"

asset_list = returns.columns[1:25].str.replace("_Price","").tolist()
print("Asset List:", asset_list)

# market capitalization list for the assets in asset_list, using yfinance to fetch market cap data
market_cap_list = []
for asset in asset_list:
    market_cap = yf.Ticker(asset).info.get("marketCap", np.nan)
    market_cap_list.append(market_cap)

print("Market Cap List:", market_cap_list)

# reverse optimization - market capitalizaiton weight for the 24 assets...
# this is constant for all rolling windows.

market_cap_weights = np.array(market_cap_list) / np.sum(market_cap_list)
print ("Market Cap Weights:\n", market_cap_weights)

return_matrix = return_matrix.dropna()
print ("Return Matrix:\n", return_matrix.head())

trading_days_per_month = return_matrix.groupby(pd.Grouper(freq="ME")).size()
print ("Trading Days per Month:\n", trading_days_per_month)

# risk-free rate taken from the FRB St. Louis FRED database, 3-month Treasury Bill rate
# this rate will depend on the end date for each rolling period.

risk_free_url = "https://fred.stlouisfed.org/graph/fredgraph.csv?id=DGS3MO"
risk_free = pd.read_csv(risk_free_url, parse_dates=["observation_date"])
risk_free = risk_free.rename(columns={"observation_date": "Date", "DGS3MO": "Risk_Free_Rate"})
risk_free = risk_free.set_index("Date")
risk_free["Risk_Free_Rate"] = pd.to_numeric(risk_free["Risk_Free_Rate"], errors='coerce') 
#avoid non-numeric errors.
risk_free["Risk_Free_Rate"] = risk_free["Risk_Free_Rate"].ffill() / 100
risk_free = risk_free.reindex(return_matrix.index).ffill()
#print ("Risk Free Rate:\n", risk_free.head())

benchmark_returns = return_matrix.dot(market_cap_weights)
#print ("Benchmark Returns:\n", benchmark_returns)

total_rows = return_matrix.shape[0]
rolling_period = return_matrix[return_matrix.index.year == 2020].shape[0] # number of daily returns
total_months = return_matrix.groupby(pd.Grouper(freq="ME")).tail(1).index # number of months
#print ("Total Months:", total_months)

print("No. of rows per rolling period:", rolling_period)

rolling_windows = sum(return_matrix.index.get_loc(date) >= rolling_period 
                      for date in total_months)
print ("Rolling Windows:", rolling_windows)

# code for Black Litterman Views - 4 in total.

def BLO_views(asset_list,view_dict):
    row=np.zeros(len(asset_list))
    for asset, weight in view_dict.items():
        row[asset_list.index(asset)] = weight
    return row

# adding the 4 views to the matrices P and Q (investor views)
P = np.array([BLO_views(asset_list, {"NVDA": 1}),
                BLO_views(asset_list, {"LMT": 1, "MSFT": -1}),
                BLO_views(asset_list, {"TEL": 1, "MU": -1}),
                BLO_views(asset_list, {"MRVL": 1})])
Q = np.array([0.025, 0.01, 0.01, 0.015])
print("P Matrix:\n", P)
print("Q Vector:\n", Q)

# end of code for Black Litterman Views

tau = 0.035
confidence_level = 0.50
confidence_levels = np.full(len(Q), confidence_level)
print ("Confidence Levels:\n", confidence_levels)


rolling_window_count = 0

for i, end_date in enumerate(total_months):
    end_loc = return_matrix.index.get_loc(end_date)
    if end_loc < rolling_period:
        continue

    rolling_window_count += 1
    rolling_window_returns = return_matrix.iloc[end_loc - rolling_period + 1:end_loc + 1]
    rolling_window_end_date = rolling_window_returns.index[-1]

    mean_rolling_returns = rolling_window_returns.mean()
    rolling_cov_matrix = rolling_window_returns.cov()
    rolling_standard_deviation = rolling_window_returns.std()
    
    rolling_benchmark_returns = rolling_window_returns.dot(market_cap_weights)

    annualized_benchmark_returns = rolling_benchmark_returns.mean() * 252
    annualized_benchmark_variance = rolling_benchmark_returns.var() * 252

    rolling_risk_free_rate = risk_free["Risk_Free_Rate"].asof(rolling_window_end_date)

    risk_aversion_coefficient = (annualized_benchmark_returns - rolling_risk_free_rate) / annualized_benchmark_variance
    risk_aversion_coefficient = max(risk_aversion_coefficient, 1)  # Ensure a minimum value of 1.
    annualized_rolling_cov_matrix = rolling_cov_matrix * 252

    implied_equilibrium_returns = risk_aversion_coefficient * annualized_rolling_cov_matrix.dot(market_cap_weights)

    rolling_omega = np.diag(np.diag(P @ (tau * annualized_rolling_cov_matrix) @(P.T))) * (1 - confidence_level) / confidence_level
    tau_sigma = tau * annualized_rolling_cov_matrix

    posterior_cov_inverse = np.linalg.inv(tau_sigma) + P.T @ np.linalg.inv(rolling_omega) @ P
    posterior_returns = np.linalg.inv(posterior_cov_inverse) @ (np.linalg.inv(tau_sigma) @ implied_equilibrium_returns + P.T @ np.linalg.inv(rolling_omega) @ Q)

    #print ("Rolling Omega Matrix:\n", rolling_omega)
    #print("Rolling Window:", rolling_window_count)
    #print("Window End Date:", rolling_window_end_date)
    #print("Risk Free Rate:", rolling_risk_free_rate)
    #print("Risk Aversion:", risk_aversion_coefficient)
    #print("Implied Equilibrium Returns:\n", implied_equilibrium_returns)
    #print ("Risk Aversion Coefficient:", risk_aversion_coefficient)
    #print("Rolling Window Count:", rolling_window_count)
    #print(f"Rolling Window {rolling_window_count}:")
    #print(f"Start Date:{rolling_window_returns.index[0]}")
    #print(f"End Date:{rolling_window_returns.index[-1]}")
    #print("Mean Rolling Returns:\n", mean_rolling_returns)
    #print("Rolling Covariance Matrix:\n", rolling_cov_matrix)






